### ISSUE TITLE
Lebab can't convert function construction to Class based construction

### ISSUE THREAD

**Issue by syedsimanta03** [uniibu/lebab-ce#163]
`// Types.js - Constructors used behind the scenes

// A constructor for defining new cars
function Car({doors, state, color}) {
  // some defaults
  this.doors = doors || 4;
  this.state = state || 'brand new';
  this.color = color || 'silver';
}

// A constructor for defining new trucks
function Truck({state, wheelSize, color}) {
  this.state = state || 'used';
  this.wheelSize = wheelSize || 'large';
  this.color = color || 'blue';
}

// FactoryExample.js

// Define a skeleton vehicle factory
class VehicleFactory {
  // Our Factory method for creating new Vehicle instances
  createVehicle(options) {
    switch (options.vehicleType) {
      case 'car':
        this.vehicleClass = Car;
        break;
      case 'truck':
        this.vehicleClass = Truck;
        break;
      //defaults to VehicleFactory.prototype.vehicleClass (Car)
    }

    return new this.vehicleClass(options);
  }
}

// Define the prototypes and utilities for this factory

// Our default vehicleClass is Car
VehicleFactory.prototype.vehicleClass = Car;

// Create an instance of our factory that makes cars
const carFactory = new VehicleFactory();
const car = carFactory.createVehicle({
  vehicleType: 'car',
  color: 'yellow',
  doors: 6
});

// Test to confirm our car was created using the vehicleClass/prototype Car

// Outputs: true
console.log(car instanceof Car);

// Outputs: Car object of color "yellow", doors: 6 in a "brand new" state
console.log(car);`

Unable to convert it poperly in es6. Just try: a lot to improve

**Comment by uniibu** [comment]
Not the correct repo for this issue. Create one at https://github.com/lebab/lebab
