### ISSUE TITLE
bug: multiple errors in the last version running in localhost

### ISSUE THREAD

**Issue by rbatllet** [uniibu/lebab-ce#34]
It doesn't work, too many warnings:

![Screenshot 2019-05-13 at 20 57 06](https://user-images.githubusercontent.com/3993987/57646855-dbe70880-75c1-11e9-919b-1623dcb27b6e.png)

**Comment by rbatllet** [comment]
The online version does not work either -> https://lebab.unibtc.me/editor

**Comment by uniibu** [comment]
https://lebab.unibtc.me/editor has been working fine
